<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RollForward>LatestMajor</RollForward>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlightScanner.Common\FlightScanner.Common.csproj" />
  </ItemGroup>

</Project>
